# Generated by Django 2.0 on 2018-01-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttomainpage',
            old_name='title',
            new_name='helyszin',
        ),
        migrations.RenameField(
            model_name='posttomainpage',
            old_name='published_date',
            new_name='idopont',
        ),
        migrations.RemoveField(
            model_name='posttomainpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posttomainpage',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='posttomainpage',
            name='text',
        ),
    ]
